spring:
  application:
    name: config-server
  
  output:
    ansi:
      enabled: ALWAYS

  profiles:
    active: native
  
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config 

server:
  port: 8888